# fly.toml app configuration file generated for hikegroop on 2023-10-30T12:34:11+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "hikegroop"
primary_region = "sin"

[env]
  ASPNETCORE_URLS="http://+:8080"
  CloudinarySettings__CloudName = "dr04ygceb"
  CloudinarySettings__ApiKey = "361478783915649"
  

[build]
  image = "cathleyson/hikegroop:latest"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
